### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by pqw71647** [RamAlapure/JavaFXSpringBootApp#2]
I followed your instructions except I create project in netbeans. But it cause this error (when sign in):

> Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1774)
.
.
.
        at com.codetreatise.service.impl.UserServiceImpl.findByEmail(UserServiceImpl.java:61)
	at com.codetreatise.service.impl.UserServiceImpl.authenticate(UserServiceImpl.java:50)
	at com.codetreatise.controller.LoginController.login(LoginController.java:53)
```
//This function cause java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	@Override
	public User findByEmail(String email) {
		return userRepository.findByEmail(email);
	}
```
What to do to fix this?

This is full console log.
[log.txt](https://github.com/RamAlapure/JavaFXSpringBootApp/files/1471028/log.txt)

**Comment by pqw71647** [comment]
I tried to go through the RuntimeException above so I commented authenticate part like this:

`	@FXML
    private void login(ActionEvent event) throws IOException{
//    	if(userService.authenticate(getUsername(), getPassword())){
//    		    		
    		stageManager.switchScene(FxmlView.USER);
//    		
//    	}else{
//    		lblLogin.setText("Login Failed.");
//    	}
    }`
And it cause catched exception, log and end this program:
[log.txt](https://github.com/RamAlapure/JavaFXSpringBootApp/files/1471054/log.txt)

**Comment by RamAlapure** [comment]
The problem found from your log.txt is it's unable to load user.fxml
`2017-11-14 15:04:20.508 ERROR 6716 --- [lication Thread] com.codetreatise.config.StageManager     : Unable to load FXML view/fxml/User.fxml`
have changed anything or modified path?
